### ISSUE TITLE
FAQ Section

### ISSUE THREAD

**Issue by ChristianBirchler** [skhatiri/Aerialist#8]
As a user I want to have quick answers to common issues so that I can speed up my development.

Suggestions:
- Provide a FAQ section
- Provide a Slack or Discord channel for quick answers (especially for the tool competition)

**Comment by skhatiri** [comment]
Thanks for the suggestion, I enabled the [discussion section](https://github.com/skhatiri/Aerialist/discussions) to facilitate this. 
Hopefully, it will grow to include all common QAs.
